server:
  port: 8080
  servlet:
    context-path: /sistema
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=relacionamentos
    username: teste_relations
    password: M3rdaGr0ssa
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: sql_server
    properties:
      hibernate:
        generate_statistics: true
        order_inserts: true
        jdbc:
          batch_size: 200
