server:
  port: 8080
  servlet:
    context-path: /sistema
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${ENV_DB_HOST}:${ENV_DB_PORT}/relacionamentos
    username: ${ENV_DB_USERNAME}
    password: ${ENV_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
  flyway:
    user: ${ENV_DB_FLYWAY_USERNAME}
    password: ${ENV_DB_FLYWAY_PASSWORD}
    url: jdbc:postgresql://${ENV_DB_HOST}:${ENV_DB_PORT}/relacionamentos
springdoc:
  packages-to-scan: br.com.edwi.jpa.relacionamentos.controllers
